#!/usr/bin/env python3

import getopt
import sys
from collections import OrderedDict

import simplejson as json
import xlrd
from deepmerge import always_merger
from unflatten import unflatten


def createJSON(input_file, output_file, lang, keyColumn):
    wb = xlrd.open_workbook(input_file)
    sh = wb.sheet_by_index(0)
    translation = {}

    translationColumn = sh.row_values(0).index(lang)

    for rownum in range(1, sh.nrows):
        data = OrderedDict()
        row_values = sh.row_values(rownum)
        data['translate_key'] = row_values[keyColumn]
        data['translation'] = row_values[translationColumn]

        t = unflatten({data['translate_key']: data['translation']})
        translation = always_merger.merge(translation, t)

    j = json.dumps(translation)

    with open(output_file, 'w') as f:
        f.write(j)
    print('\nSuccess, output written in ->', output_file)


if __name__ == "__main__":
    argv = sys.argv[1:]
    input_file = 'translate-file.xlsx'
    output_file = 'fr.json'
    lang = 'fr'
    keyColumn = 1
    try:
        opts, args = getopt.getopt(argv, "hi:o:l:k",
                                   ["ifile=", "ofile=", "lang=", "keycolumn="])
    except getopt.GetoptError:
        print('xlsxToJsonTranslate -i <inputfile> '
              '-o <outputfile> -l <lang> -k <keycolumn>')
        sys.exit(2)
    for opt, arg in opts:
        if opt == '-h':
            print('xlsxToJsonTranslate -i <inputfile> '
                  '-o <outputfile> -l <lang> -k <keycolumn>')
            sys.exit()
        elif opt in ("-i", "--ifile"):
            input_file = arg
        elif opt in ("-o", "--ofile"):
            output_file = arg
        elif opt in ("-l", "--lang"):
            lang = arg
        elif opt in ("-k", "--keycolumn"):
            keyColumn = arg
    print('Input file is :', input_file)
    print('Output file is :', output_file)
    print('Lang is :', lang)
    print('KeyColumn is :', keyColumn)
    createJSON(input_file, output_file, lang, keyColumn)
